// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrqpSl6Sd3NR3FORIUP8MDZECHGs0O4dI',
    appId: '1:921274923536:web:43433b00318a1371e86895',
    messagingSenderId: '921274923536',
    projectId: 'pora-lekha-65fd6',
    authDomain: 'pora-lekha-65fd6.firebaseapp.com',
    databaseURL:
        'https://pora-lekha-65fd6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pora-lekha-65fd6.appspot.com',
    measurementId: 'G-MEQRM889TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEG-ELOpOx38jFtnhHZ87e2atPkGMHnDs',
    appId: '1:921274923536:android:e340e53d14836055e86895',
    messagingSenderId: '921274923536',
    projectId: 'pora-lekha-65fd6',
    databaseURL:
        'https://pora-lekha-65fd6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pora-lekha-65fd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxHfGacY_h47x2XJE88YqrJ8PNhPn4JN0',
    appId: '1:921274923536:ios:4791d457c273d348e86895',
    messagingSenderId: '921274923536',
    projectId: 'pora-lekha-65fd6',
    databaseURL:
        'https://pora-lekha-65fd6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pora-lekha-65fd6.appspot.com',
    iosClientId:
        '921274923536-piqrnu9evkismooj77028b6vd7gdi6fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.poraLekha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxHfGacY_h47x2XJE88YqrJ8PNhPn4JN0',
    appId: '1:921274923536:ios:4791d457c273d348e86895',
    messagingSenderId: '921274923536',
    projectId: 'pora-lekha-65fd6',
    databaseURL:
        'https://pora-lekha-65fd6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pora-lekha-65fd6.appspot.com',
    iosClientId:
        '921274923536-piqrnu9evkismooj77028b6vd7gdi6fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.poraLekha',
  );
}
